version: 2
jobs:
  build:
    
    working_directory: ~/whiteboard-spring

    docker:
      - image: circleci/openjdk:8u171-jdk
      - image: circleci/postgres:9.6.3-alpine

        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:

      - checkout

      - restore_cache:
          key: whiteboard-spring-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: whiteboard-spring-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
          
      - store_artifacts:
         path: target/WhiteboardSpring-0.0.1-SNAPSHOT.jar
         
    deploy:
        machine:
          enabled: true
        steps:
          - run:
              name: Deploy Over SSH
              command: |
                ssh -i C:\Users\James\.ssh\WhiteboardCI 129.213.52.63 -l ubuntu
                git pull
                mvn spring-boot:run