version: 2 # use CircleCI 2.0
jobs: # a collection of steps
    build: # runs not using Workflows must have a `build` job as entry point
        working_directory: ~/WhiteboardSpring # directory where steps will run
        
        docker:
            - image: circleci/openjdk:8-jdk-browsers
        
        steps:
          - checkout

          - restore_cache:
              key: WhiteboardSpring-{{ checksum "pom.xml" }}
          
          - run: mvn dependency:go-offline
          
          - save_cache:
              paths:
                - ~/.m2
              key: WhiteboardSpring-{{ checksum "pom.xml" }}
          
          - run: mvn package
          
          - store_test_results:
              path: target/surefire-reports
          
          - store_artifacts:
              path: target/demo-java-spring-0.0.1-SNAPSHOT.jar